from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest
import yaml

from src.backtest.calendar import KRXTradingCalendar
from src.backtest.costs import Costs
from src.features.macro_regime import factor_aggregation_composite
from src.run_experiment import _d001_blocks_from_config
from src.strategies.d008_subperiod_analysis import run_d008_variants


CONFIG_PATH = Path("configs/backtests/d008.yaml")
D001_METRICS_PATH = Path("reports/experiments/D001_factor_aggregation_pivot/metrics.json")
D008_FULL_METRICS_PATH = Path("reports/experiments/D008_oos_subperiod_split/full/metrics.json")
D008_A_IS_METRICS_PATH = Path("reports/experiments/D008_oos_subperiod_split/scheme_a_is/metrics.json")
D008_A_OOS_METRICS_PATH = Path("reports/experiments/D008_oos_subperiod_split/scheme_a_oos/metrics.json")


def test_d008_config_is_d001_with_subperiods_only() -> None:
    config = _load_config()
    d001 = yaml.safe_load(Path("configs/backtests/d001.yaml").read_text(encoding="utf-8"))

    assert config["regime"] == d001["regime"]
    assert config["selection"] == d001["selection"]
    assert config["costs"] == d001["costs"]
    assert config["rebalance"] == d001["rebalance"]
    assert [item["name"] for item in config["subperiods"]] == [
        "full",
        "scheme_a_is",
        "scheme_a_oos",
        "scheme_b_is",
        "scheme_b_oos",
        "scheme_c_is",
        "scheme_c_oos",
    ]


def test_d008_full_period_reproduces_d001_metrics_when_outputs_exist() -> None:
    if not D008_FULL_METRICS_PATH.exists():
        pytest.skip("D008 metrics are generated by the D008 backtest run.")
    d001 = json.loads(D001_METRICS_PATH.read_text(encoding="utf-8"))
    d008 = json.loads(D008_FULL_METRICS_PATH.read_text(encoding="utf-8"))

    assert d008["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(
        d001["factor_macro_gate_mcap"]["sharpe"],
        abs=0.0,
    )
    assert d008["factor_macro_gate_mcap"]["cumulative_net_total_return"] == pytest.approx(
        d001["factor_macro_gate_mcap"]["cumulative_net_total_return"],
        abs=0.0,
    )
    assert d008["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(0.4842, abs=0.00005)
    assert d008["factor_macro_gate_mcap"]["cumulative_net_total_return"] == pytest.approx(1.2907, abs=0.00005)


def test_d008_restricted_periods_produce_different_outputs_when_outputs_exist() -> None:
    if not D008_A_IS_METRICS_PATH.exists() or not D008_A_OOS_METRICS_PATH.exists():
        pytest.skip("D008 subperiod metrics are generated by the D008 backtest run.")
    a_is = json.loads(D008_A_IS_METRICS_PATH.read_text(encoding="utf-8"))
    a_oos = json.loads(D008_A_OOS_METRICS_PATH.read_text(encoding="utf-8"))

    assert a_is["factor_macro_gate_mcap"]["trade_count"] != a_oos["factor_macro_gate_mcap"]["trade_count"]
    assert a_is["factor_macro_gate_mcap"]["cumulative_net_total_return"] != pytest.approx(
        a_oos["factor_macro_gate_mcap"]["cumulative_net_total_return"],
        abs=0.0,
    )


def test_d008_trading_window_only_filters_quarterly_executions() -> None:
    dates = pd.to_datetime(["2025-03-31", "2025-04-01", "2025-06-30", "2025-07-01"])
    calendar = KRXTradingCalendar(dates)

    runs, candidates = run_d008_variants(
        panel=_panel(dates),
        calendar=calendar,
        universe=_universe(dates),
        quarterly_regime=_quarterly_regime(["2025-03-31", "2025-06-30"], [True, True]),
        market_breadth=_market_breadth(dates),
        costs=Costs(commission_bps=0.0, tax_bps_sell=0.0, slippage_bps=0.0),
        segments=((dates[0], dates[-1]),),
        max_positions=5,
        trading_start="2025-07-01",
        trading_end="2025-07-01",
    )

    assert set(runs) == {"factor_macro_gate_mcap", "kospi_buy_and_hold", "cash"}
    assert candidates["factor_macro_gate_mcap"]["signal_date"].unique().tolist() == [pd.Timestamp("2025-06-30")]
    assert runs["factor_macro_gate_mcap"].trades["entry_date"].tolist() == [pd.Timestamp("2025-07-01")] * 5
    assert all(runs["factor_macro_gate_mcap"].trades["entry_date"] > runs["factor_macro_gate_mcap"].trades["signal_date"])


def test_d008_zscore_at_trade_quarter_uses_no_future_rows() -> None:
    dates = pd.date_range("2010-01-31", periods=62, freq="ME")
    before = _factor_regime_frame(dates)
    after = before.copy()
    after.loc[61, after.columns.difference(["signal_date"])] = 9999.0
    blocks = _d001_blocks_from_config(_load_config()["regime"]["blocks"])

    before_result = factor_aggregation_composite(before, z_score_window_months=60, blocks=blocks)
    after_result = factor_aggregation_composite(after, z_score_window_months=60, blocks=blocks)

    columns = [column for column in before_result.columns if column.endswith("_z") or column.startswith("block_")]
    columns.extend(["composite", "regime_on"])
    pd.testing.assert_series_equal(before_result.loc[60, columns], after_result.loc[60, columns])


def _load_config() -> dict[str, object]:
    return yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))


def _factor_regime_frame(dates: pd.DatetimeIndex) -> pd.DataFrame:
    base = pd.Series(range(1, len(dates) + 1), dtype="float64")
    values = base + (base.mod(7) * 0.5)
    reverse = values.iloc[::-1].reset_index(drop=True)
    return pd.DataFrame(
        {
            "signal_date": dates,
            "USDKRW_yoy": values,
            "VIX_60d_avg": values,
            "VIX_240d_avg": [1.0] * len(dates),
            "DXY_yoy": reverse,
            "US_2_10_curve_spread": values,
            "Brent_yoy": values,
            "KR10Y_yoy_change": reverse,
            "US_CPI_decel": values,
            "US_PPI_decel": reverse,
        }
    )


def _panel(dates: pd.DatetimeIndex) -> pd.DataFrame:
    rows = []
    for date_index, date in enumerate(dates):
        for ticker_index in range(6):
            rows.append(
                {
                    "날짜": date,
                    "종목코드": f"00000{ticker_index}",
                    "시가": 100.0 + date_index,
                    "KRX종가": 101.0 + date_index,
                    "상장주식수": 1_000_000 + ticker_index,
                }
            )
    return pd.DataFrame(rows)


def _universe(dates: pd.DatetimeIndex) -> pd.DataFrame:
    rows = []
    for signal_date, execution_date in zip(dates[:-1], dates[1:], strict=False):
        for ticker_index in range(6):
            rows.append(
                {
                    "execution_date": execution_date,
                    "signal_date": signal_date,
                    "종목코드": f"00000{ticker_index}",
                }
            )
    return pd.DataFrame(rows)


def _quarterly_regime(signal_dates: list[str], regime_on: list[bool]) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "signal_date": pd.to_datetime(signal_dates),
            "composite": [0.1 if on else -0.1 for on in regime_on],
            "regime_score": [0.1 if on else -0.1 for on in regime_on],
            "regime_on": regime_on,
        }
    )


def _market_breadth(dates: pd.DatetimeIndex) -> pd.DataFrame:
    return pd.DataFrame({"date": dates, "cap_weighted_return": [0.0] + [0.01] * (len(dates) - 1)})
