from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest
import yaml

from src.features.macro_regime import factor_aggregation_composite
from src.run_experiment import _d001_blocks_from_config


CONFIG_PATH = Path("configs/backtests/d012.yaml")
D009_METRICS_PATH = Path("reports/experiments/D009_chatgpt_holistic_design/metrics.json")
D012_FULL_METRICS_PATH = Path("reports/experiments/D012_d009_oos_subperiod/full/metrics.json")


def test_d012_config_is_d009_with_subperiods_only() -> None:
    config = _load_config()
    d009 = yaml.safe_load(Path("configs/backtests/d009.yaml").read_text(encoding="utf-8"))

    assert config["regime"] == d009["regime"]
    assert config["selection"] == d009["selection"]
    assert config["costs"] == d009["costs"]
    assert config["rebalance"] == d009["rebalance"]
    assert [item["name"] for item in config["subperiods"]] == [
        "full",
        "scheme_a_is",
        "scheme_a_oos",
        "scheme_b_is",
        "scheme_b_oos",
        "scheme_c_is",
        "scheme_c_oos",
    ]


def test_d012_full_period_reproduces_d009_metrics_when_outputs_exist() -> None:
    if not D012_FULL_METRICS_PATH.exists():
        pytest.skip("D012 metrics are generated by the D012 backtest run.")
    d009 = json.loads(D009_METRICS_PATH.read_text(encoding="utf-8"))
    d012 = json.loads(D012_FULL_METRICS_PATH.read_text(encoding="utf-8"))

    assert d012["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(d009["factor_macro_gate_mcap"]["sharpe"], abs=0.0)
    assert d012["factor_macro_gate_mcap"]["cumulative_net_total_return"] == pytest.approx(
        d009["factor_macro_gate_mcap"]["cumulative_net_total_return"],
        abs=0.0,
    )
    assert d012["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(0.36524689410364136, abs=0.00005)


def test_d012_zscore_at_trade_quarter_uses_no_future_rows() -> None:
    dates = pd.date_range("2010-01-31", periods=62, freq="ME")
    before = _factor_regime_frame(dates)
    after = before.copy()
    after.loc[61, after.columns.difference(["signal_date"])] = 9999.0
    blocks = _d001_blocks_from_config(_load_config()["regime"]["blocks"])

    before_result = factor_aggregation_composite(before, z_score_window_months=60, blocks=blocks)
    after_result = factor_aggregation_composite(after, z_score_window_months=60, blocks=blocks)

    columns = [column for column in before_result.columns if column.endswith("_z") or column.startswith("block_")]
    columns.extend(["composite", "regime_on"])
    pd.testing.assert_series_equal(before_result.loc[60, columns], after_result.loc[60, columns])


def _load_config() -> dict[str, object]:
    return yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))


def _factor_regime_frame(dates: pd.DatetimeIndex) -> pd.DataFrame:
    base = pd.Series(range(1, len(dates) + 1), dtype="float64")
    reverse = base.iloc[::-1].reset_index(drop=True)
    return pd.DataFrame(
        {
            "signal_date": dates,
            "USDKRW_yoy": base,
            "VIX_60d_avg": base,
            "VIX_240d_avg": [1.0] * len(dates),
            "DXY_yoy": reverse,
            "US_2_10_curve_spread": base + 0.1,
            "Brent_yoy": reverse + 0.2,
            "BAA10Y_spread_level": base + 0.3,
            "US_10Y_real_level": reverse + 0.4,
            "US_breakeven_level": base + 0.5,
            "KR_exports_yoy": reverse + 0.6,
            "KR_CLI_value": base + 100.0,
        }
    )
