from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest
import yaml

from src.features.macro_regime import factor_aggregation_composite
from src.run_experiment import _d001_blocks_from_config


CONFIG_PATH = Path("configs/backtests/d011.yaml")
D009_METRICS_PATH = Path("reports/experiments/D009_chatgpt_holistic_design/metrics.json")
D011_0_METRICS_PATH = Path("reports/experiments/D011_d009_threshold_grid/threshold_p0p0/metrics.json")


def test_d011_config_is_d009_threshold_grid_only() -> None:
    config = _load_config()
    d009 = yaml.safe_load(Path("configs/backtests/d009.yaml").read_text(encoding="utf-8"))

    assert config["regime"]["z_score_window_months"] == 60
    assert config["regime"]["on_threshold_grid"] == [-0.2, -0.1, 0.0, 0.1, 0.2]
    assert _d001_blocks_from_config(config["regime"]["blocks"]) == _d001_blocks_from_config(d009["regime"]["blocks"])
    assert config["selection"] == d009["selection"]
    assert config["costs"] == d009["costs"]
    assert config["rebalance"] == d009["rebalance"]


def test_d011_threshold_zero_reproduces_d009_metrics_when_outputs_exist() -> None:
    if not D011_0_METRICS_PATH.exists():
        pytest.skip("D011 threshold 0.0 metrics are generated by the D011 backtest run.")
    d009 = json.loads(D009_METRICS_PATH.read_text(encoding="utf-8"))
    d011 = json.loads(D011_0_METRICS_PATH.read_text(encoding="utf-8"))

    assert d011["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(d009["factor_macro_gate_mcap"]["sharpe"], abs=0.0)
    assert d011["factor_macro_gate_mcap"]["cumulative_net_total_return"] == pytest.approx(
        d009["factor_macro_gate_mcap"]["cumulative_net_total_return"],
        abs=0.0,
    )
    assert d011["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(0.4144, abs=0.00005)


def test_d011_threshold_grid_produces_different_outputs() -> None:
    dates = pd.date_range("2010-01-31", periods=90, freq="ME")
    regime = _factor_regime_frame(dates)
    blocks = _d001_blocks_from_config(_load_config()["regime"]["blocks"])

    result_loose = factor_aggregation_composite(regime, z_score_window_months=60, on_threshold=-0.2, blocks=blocks)
    result_strict = factor_aggregation_composite(regime, z_score_window_months=60, on_threshold=0.2, blocks=blocks)

    pd.testing.assert_series_equal(result_loose["composite"], result_strict["composite"])
    assert result_loose["regime_on"].sum() != result_strict["regime_on"].sum()


def test_d011_threshold_uses_no_future_rows() -> None:
    dates = pd.date_range("2010-01-31", periods=85, freq="ME")
    before = _factor_regime_frame(dates)
    after = before.copy()
    after.loc[84, after.columns.difference(["signal_date"])] = 9999.0
    blocks = _d001_blocks_from_config(_load_config()["regime"]["blocks"])

    before_result = factor_aggregation_composite(before, z_score_window_months=60, on_threshold=0.1, blocks=blocks)
    after_result = factor_aggregation_composite(after, z_score_window_months=60, on_threshold=0.1, blocks=blocks)

    columns = [column for column in before_result.columns if column.endswith("_z") or column.startswith("block_")]
    columns.extend(["composite", "regime_on"])
    pd.testing.assert_series_equal(before_result.loc[83, columns], after_result.loc[83, columns])


def _load_config() -> dict[str, object]:
    return yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))


def _factor_regime_frame(dates: pd.DatetimeIndex) -> pd.DataFrame:
    base = pd.Series(range(1, len(dates) + 1), dtype="float64")
    reverse = base.iloc[::-1].reset_index(drop=True)
    return pd.DataFrame(
        {
            "signal_date": dates,
            "USDKRW_yoy": base,
            "VIX_60d_avg": base,
            "VIX_240d_avg": [1.0] * len(dates),
            "DXY_yoy": reverse,
            "US_2_10_curve_spread": base + 0.1,
            "Brent_yoy": reverse + 0.2,
            "BAA10Y_spread_level": base + 0.3,
            "US_10Y_real_level": reverse + 0.4,
            "US_breakeven_level": base + 0.5,
            "KR_exports_yoy": reverse + 0.6,
            "KR_CLI_value": base + 100.0,
        }
    )
