from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest
import yaml

from src.backtest.calendar import KRXTradingCalendar
from src.backtest.costs import Costs
from src.features.macro_regime import factor_aggregation_composite
from src.run_experiment import _d001_blocks_from_config
from src.strategies.d007_threshold_grid import run_d007_variants


CONFIG_PATH = Path("configs/backtests/d007.yaml")
D001_METRICS_PATH = Path("reports/experiments/D001_factor_aggregation_pivot/metrics.json")
D007_0_METRICS_PATH = Path("reports/experiments/D007_threshold_neighborhood_grid/threshold_p0p0/metrics.json")


def test_d007_config_is_d001_threshold_grid_only() -> None:
    config = _load_config()
    d001 = yaml.safe_load(Path("configs/backtests/d001.yaml").read_text(encoding="utf-8"))

    assert config["regime"]["z_score_window_months"] == 60
    assert config["regime"]["on_threshold_grid"] == [-0.2, -0.1, 0.0, 0.1, 0.2]
    assert _d001_blocks_from_config(config["regime"]["blocks"]) == _d001_blocks_from_config(d001["regime"]["blocks"])
    assert config["selection"] == d001["selection"]
    assert config["costs"] == d001["costs"]
    assert config["rebalance"] == d001["rebalance"]


def test_d007_threshold_zero_reproduces_d001_metrics_when_outputs_exist() -> None:
    if not D007_0_METRICS_PATH.exists():
        pytest.skip("D007 threshold 0.0 metrics are generated by the D007 backtest run.")
    d001 = json.loads(D001_METRICS_PATH.read_text(encoding="utf-8"))
    d007 = json.loads(D007_0_METRICS_PATH.read_text(encoding="utf-8"))

    assert d007["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(
        d001["factor_macro_gate_mcap"]["sharpe"],
        abs=0.0,
    )
    assert d007["factor_macro_gate_mcap"]["cumulative_net_total_return"] == pytest.approx(
        d001["factor_macro_gate_mcap"]["cumulative_net_total_return"],
        abs=0.0,
    )
    assert d007["factor_macro_gate_mcap"]["sharpe"] == pytest.approx(0.4842, abs=0.00005)


def test_d007_threshold_grid_produces_different_outputs() -> None:
    dates = pd.date_range("2010-01-31", periods=90, freq="ME")
    regime = _factor_regime_frame(dates)
    blocks = _d001_blocks_from_config(_load_config()["regime"]["blocks"])

    result_loose = factor_aggregation_composite(regime, z_score_window_months=60, on_threshold=-0.2, blocks=blocks)
    result_strict = factor_aggregation_composite(regime, z_score_window_months=60, on_threshold=0.2, blocks=blocks)

    pd.testing.assert_series_equal(result_loose["composite"], result_strict["composite"])
    assert result_loose["regime_on"].sum() != result_strict["regime_on"].sum()


def test_d007_threshold_uses_no_future_rows() -> None:
    dates = pd.date_range("2010-01-31", periods=85, freq="ME")
    before = _factor_regime_frame(dates)
    after = before.copy()
    after.loc[84, after.columns.difference(["signal_date"])] = 9999.0
    blocks = _d001_blocks_from_config(_load_config()["regime"]["blocks"])

    before_result = factor_aggregation_composite(before, z_score_window_months=60, on_threshold=0.1, blocks=blocks)
    after_result = factor_aggregation_composite(after, z_score_window_months=60, on_threshold=0.1, blocks=blocks)

    columns = [column for column in before_result.columns if column.endswith("_z") or column.startswith("block_")]
    columns.extend(["composite", "regime_on"])
    pd.testing.assert_series_equal(before_result.loc[83, columns], after_result.loc[83, columns])


def test_d007_factor_quarterly_gate_uses_next_day_execution() -> None:
    dates = pd.to_datetime(["2025-03-31", "2025-04-01", "2025-06-30", "2025-07-01"])
    calendar = KRXTradingCalendar(dates)

    runs, candidates = run_d007_variants(
        panel=_panel(dates),
        calendar=calendar,
        universe=_universe(dates),
        quarterly_regime=_quarterly_regime(["2025-03-31", "2025-06-30"], [True, False]),
        market_breadth=_market_breadth(dates),
        costs=Costs(commission_bps=0.0, tax_bps_sell=0.0, slippage_bps=0.0),
        segments=((dates[0], dates[-1]),),
        max_positions=5,
    )

    assert set(runs) == {"factor_macro_gate_mcap", "kospi_buy_and_hold", "cash"}
    assert candidates["factor_macro_gate_mcap"]["signal_date"].unique().tolist() == [pd.Timestamp("2025-03-31")]
    assert runs["factor_macro_gate_mcap"].trades["entry_date"].tolist() == [pd.Timestamp("2025-04-01")] * 5
    assert all(runs["factor_macro_gate_mcap"].trades["entry_date"] > runs["factor_macro_gate_mcap"].trades["signal_date"])


def _load_config() -> dict[str, object]:
    return yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))


def _factor_regime_frame(dates: pd.DatetimeIndex) -> pd.DataFrame:
    base = pd.Series(range(1, len(dates) + 1), dtype="float64")
    values = base + (base.mod(7) * 0.5)
    reverse = values.iloc[::-1].reset_index(drop=True)
    return pd.DataFrame(
        {
            "signal_date": dates,
            "USDKRW_yoy": values,
            "VIX_60d_avg": values,
            "VIX_240d_avg": [1.0] * len(dates),
            "DXY_yoy": reverse,
            "US_2_10_curve_spread": values,
            "Brent_yoy": values,
            "KR10Y_yoy_change": reverse,
            "US_CPI_decel": values,
            "US_PPI_decel": reverse,
        }
    )


def _panel(dates: pd.DatetimeIndex) -> pd.DataFrame:
    rows = []
    for date_index, date in enumerate(dates):
        for ticker_index in range(6):
            rows.append(
                {
                    "날짜": date,
                    "종목코드": f"00000{ticker_index}",
                    "시가": 100.0 + date_index,
                    "KRX종가": 101.0 + date_index,
                    "상장주식수": 1_000_000 + ticker_index,
                }
            )
    return pd.DataFrame(rows)


def _universe(dates: pd.DatetimeIndex) -> pd.DataFrame:
    rows = []
    for signal_date, execution_date in zip(dates[:-1], dates[1:], strict=False):
        for ticker_index in range(6):
            rows.append(
                {
                    "execution_date": execution_date,
                    "signal_date": signal_date,
                    "종목코드": f"00000{ticker_index}",
                }
            )
    return pd.DataFrame(rows)


def _quarterly_regime(signal_dates: list[str], regime_on: list[bool]) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "signal_date": pd.to_datetime(signal_dates),
            "composite": [0.1 if on else -0.1 for on in regime_on],
            "regime_score": [0.1 if on else -0.1 for on in regime_on],
            "regime_on": regime_on,
        }
    )


def _market_breadth(dates: pd.DatetimeIndex) -> pd.DataFrame:
    return pd.DataFrame({"date": dates, "cap_weighted_return": [0.0] + [0.01] * (len(dates) - 1)})
